### DISCUSSION TITLE
How to define multiple ADDITIONAL_INSTALLS in docker compose?

### DISCUSSION THREAD

**Discussion by felix2702** [tillsteinbach/CarConnectivity-plugin-mqtt#17] [Q&A]
Hi there,
is there a way to add multiple `ADDITIONAL_INSTALLS` at once using docker compose? I want to add the seatcupra and the webui integration. A simple comma isn't working.
```
carconnectivity-mqtt:
  image: "tillsteinbach/carconnectivity-mqtt:edge"
  ports:
    - "4000:4000/tcp"
    environment:
      - ADDITIONAL_INSTALLS=carconnectivity-connector-seatcupra,carconnectivity-plugin-webui
      - TZ=Europe/Berlin
      - LANG=de_DE
      - LC_ALL=de_DE
    volumes:
      - /home/admin/carconnectivity.json:/carconnectivity.json
```

Just found this repository by accident after the seatconnect-integration for home assistant stopped working recently. Great work! Exactly what I needed! Big thanks!!

**Comment by tillsteinbach** [comment]
yes, you were very close:
```
carconnectivity-mqtt:
  image: "tillsteinbach/carconnectivity-mqtt:edge"
  ports:
    - "4000:4000/tcp"
    environment:
      - ADDITIONAL_INSTALLS=carconnectivity-connector-seatcupra carconnectivity-plugin-webui
      - TZ=Europe/Berlin
      - LANG=de_DE
      - LC_ALL=de_DE
    volumes:
      - /home/admin/carconnectivity.json:/carconnectivity.json
```
