### DISCUSSION TITLE
MQTT topics as JSON

### DISCUSSION THREAD

**Discussion by z-master42** [tillsteinbach/CarConnectivity-plugin-mqtt#21] [Q&A] [answered]
Hello,

is it possible to get MQTT topics as JSON?

I am currently failing to build the topics provided via the Seat/Cupra Connector below position (i.e. longitude and latitude) in Home Assistant as MQTT device tracker.

The topic position has longitude and latitude as suptopics. In order to be able to build this in Home Assistant as a device tracker, however, I need this best as JSON on the topic position, i.e. {“longitude”: xxxx, “latitude”: yyyyy} as the value of position, since it is not possible to assemble an entity from several topics.

**Comment by tillsteinbach** [comment]
Are you sure it is not possible? I'm thinking of adding again a raw json topic with all data, but that will need time to implement again.

**Reply by z-master42** [reply]
I'm not sure, but the way I read it from the information available, it is not possible to create an entity from the contents of several subtopics.

https://www.home-assistant.io/integrations/device_tracker.mqtt/

**Comment by Pulpyyyy** [comment]
I also made several tests, but I didn't succeed.

**Reply by z-master42** [reply]
What would be possible is to first create both as separate entities and then use them as triggers for an automation, which can then be used to assemble a new MQTT topic with a usable JSON payload as an action.

**Reply by z-master42** [reply, marked as answer]
I have now solved it as follows:

I have created the latitude and longitude as individual entities.
```yaml
sensor:
  - name: "Position Latitude"
    unique_id: "VSSZZZxyz12345678PositionLatitude"
    state_topic: "carconnectivity/0/garage/VSSZZZxyz12345678/position/latitude"
    value_template: "{{ value }}"
    icon: mdi:latitude
    device:
      name: "Pepper"
      identifiers: "VSSZZZxyz12345678"
      manufacturer: "Seat"
      model: "Ateca 2023"
      
  - name: "Position Longitude"
    unique_id: "VSSZZZxyz12345678PositionLongitude"
    state_topic: "carconnectivity/0/garage/VSSZZZxyz12345678/position/longitude"
    value_template: "{{ value }}"
    icon: mdi:longitude
    device:
      identifiers: "VSSZZZxyz12345678"
```
I then use these in an automation to create a new topic in the correct format.
```yaml
alias: Seat Ateca Position
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.pepper_position_latitude
      - sensor.pepper_position_longitude
conditions:
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.pepper_position_latitude
        state: unavailable
      - condition: state
        entity_id: sensor.pepper_position_latitude
        state: unknown
      - condition: state
        entity_id: sensor.pepper_position_longitude
        state: unavailable
      - condition: state
        entity_id: sensor.pepper_position_longitude
        state: unknown
actions:
  - action: mqtt.publish
    metadata: {}
    data:
      qos: "0"
      retain: true
      topic: carconnectivity/0/garage/VSSZZZxyz12345678/position_combined
      payload: >-
        {{ { "latitude": states('sensor.pepper_position_latitude') | float,
        "longitude": states('sensor.pepper_position_longitude') | float } |
        tojson }}
mode: single
```
I then built my actual device tracker entity on this topic.
```yaml
device_tracker:
  - name: "Position"
    unique_id: "VSSZZZ5F0P6524883Position"
    json_attributes_topic: "carconnectivity/0/garage/VSSZZZ5F0P6524883/position_combined"
    icon: mdi:car
    device:
      identifiers: "VSSZZZxyz12345678"
```
I then add the vehicle photo via the customize area, since, unlike a sensor entity, an MQTT device tracker entity in Home Assistant does not support an entity picture via it's configuration.
