### DISCUSSION TITLE
Can't load configuration file (Docker compose) to mounted volume

### DISCUSSION THREAD

**Discussion by H4nsie** [tillsteinbach/CarConnectivity-plugin-mqtt#69] [Q&A] [answered]
As readme describes to mount the docker compose volume:

```
    volumes:
      - /path/to/your/config/carconnectivity.json:/carconnectivity.json

```
But volumes can't mout to a file! So then /carconnectivity.json is created as a folder inside the container...

So, I tried the following, I put in an ENV for different config file:

- CONFIG_FILE="/config/carconnectivity.json"
- 
and I set my volume to:

```
    volumes:
      - ./:/config
```

But the configuration file won't load either:

```
 ✔ Container carconnectivity-mqtt-carconnectivity-mqtt-1  Recreated                                                                                                                  0.4s 
Attaching to carconnectivity-mqtt-1
carconnectivity-mqtt-1  | 2025-05-09T17:18:04+0200:CRITICAL:Could not find configuration file "/config/carconnectivity.json" ([Errno 2] No such file or directory: '"/config/carconnectivity.json"')
carconnectivity-mqtt-1  | Could not find configuration file
carconnectivity-mqtt-1 exited with code 1
```

The volume must be an absolute path. But carconnectivity-mqtt tries to load the configfile from the root?

Has anyone got this working in docker-compose?

**Comment by H4nsie** [comment, marked as answer]
Found it! It is not possible to mount a file, only a volume in docker compose. So I changed the example docker-compose.yml to this:

```
services:
  carconnectivity-mqtt:
    image: "tillsteinbach/carconnectivity-mqtt:latest"
    environment:
      - TZ=Europe/Amsterdam
      - LANG=de_DE
      - LC_ALL=de_DE
      - CONFIG_FILE=/config/conf.json
    volumes:
      - .:/config/

```

That solved it for me :-)
